### ISSUE TITLE
Python package requirements

### ISSUE THREAD

**Issue by DavidLloydNGP** [ishanmehta17/dash_template#1]
Hi,

This template doesn't work with the newest versions of dash libraries due to some breaking changes. See:
[https://dash-bootstrap-components.opensource.faculty.ai/migration-guide/](https://dash-bootstrap-components.opensource.faculty.ai/migration-guide/) for more details. I recommend making a requirement.txt file to specify which versions of the libraries you use are needed to run the template. If dash-bootstrap-components version>1.0.0 the template doesn't work.

**Comment by ishanmehta17** [comment]
Thanks for pointing out this. I have added the requirements.txt file now.
